name: Manually Build Docker image

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'image tag'
        required: true
        default: 'test'
        type: string
      dockerfile:
        description: 'docker file'
        required: true
        default: './Dockerfile'
        type: string

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}



      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ${{ inputs.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            jiamiao442/fastdfs-nginx:${{ inputs.tag }}

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: './docker-compose.yml'
          down-flags: '--volumes'
