name: Publish Docker image

on: 
  push:
    tags:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/fastdfs-nginx
            ygqygq2/fastdfs-nginx

      - name: Convert fastdfs tengine tag
        id: convert
        run: |
          DOCKER_METADATA_OUTPUT_NEW_TAGS=$(echo ${DOCKER_METADATA_OUTPUT_TAGS}-tengine|sed 's@ @-tengine,@g')
          echo "DOCKER_METADATA_OUTPUT_NEW_TAGS: $DOCKER_METADATA_OUTPUT_NEW_TAGS"
          echo "DOCKER_METADATA_OUTPUT_NEW_TAGS=${DOCKER_METADATA_OUTPUT_NEW_TAGS}" >> $GITHUB_OUTPUT

      - name: Build and push Docker images 1
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile-tengine
          push: true
          tags: ${{ steps.convert.outputs.DOCKER_METADATA_OUTPUT_NEW_TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64            

      - name: Build and push Docker images 2
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: './docker-compose.yml'
          down-flags: '--volumes'
